spring:
    application:
        name: EmployeeManagementSystem
    port: ${SERVER_PORT:8081}  # Defaults to 8081 if SERVER_PORT is not set

    datasource:
        url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:ems}?useSSL=false&serverTimezone=UTC
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
                format_sql: true

server:
    servlet:
        context-path: /api/v1

jwt:
    secret: ${JWT_SECRET}
    expiration: ${JWT_EXPIRATION_TIME:36000}
    issuer: ${JWT_ISSUER:EmployeeAuthServer}
    filter:
       excluded-paths: ${JWT_FILTER_EXCLUDED_PATHS:/public/**,/actuator/**,/swagger-ui/**,/v3/api-docs/**}
       enable-detailed-logging: ${JWT.FILTER.ENABLE.DETAILED.LOGGING:false}
    refresh-expiration: ${JWT.REFRESH.EXPIRATION:604800000}

# flyway:
#   enabled: true
#   locations: classpath:db/migration
#   baseline-on-migrate: true
